source 'https://rubygems.org'


gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'jquery-rails'
gem 'opal-jquery'
gem 'opal-rails'
gem 'turbolinks'
gem 'redson', :path => File.join(File.dirname(File.expand_path(__FILE__)), '..')