require "bundler"
require "rspec/core/rake_task"
Bundler.require

RSpec::Core::RakeTask.new

namespace :build do
  desc "Build our app to build.js"
  task :lib do
    Opal::Processor.source_map_enabled = false
    env = Opal::Environment.new
    env.append_path "lib"
    File.open("lib/out/compile_timestamp.rb", "w+") do |out|
      out << "# Generated by Ruby-JS compile task\n"
      out << "Redson::COMPILE_TIMESTAMP = '#{Time.now}'"
    end    
    File.open("public/out/redson.js", "w+") do |out|
      out << env["redson"].to_s
    end
  end

  task :app do
    Opal::Processor.source_map_enabled = false
    env = Opal::Environment.new
    env.append_path "app"
  
    File.open("public/out/hello.js", "w+") do |out|
      out << env["hello"].to_s
    end
  end
end

desc "open the demo page in a browser"
task :launch do
  `open public/index.html`
end

desc "guard task"
task :build => ["build:lib", "build:app"]

task :default => ["build:lib", "build:app"]