require "opal"
require "opal-jquery"

require "redson/ext/element"
require "redson/version"
require "redson/binding"
require "redson/form"
require "redson/model"
require "redson/view"
require "redson/widget"
require "out/compile_timestamp" # generated by js build task
