require "opal"
require "opal-jquery"
require "ext/element"
require "redson/version"
require "redson/binding"
require "redson/model"
require "redson/view"
require "redson/widget"
require "out/compile_timestamp" # generated by js build task
